# -*- coding: utf-8 -*-
"""project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HTfc5Ku1LOVwTXm4Xt09LFWA0R-wLCk3
"""

!pip install fasttext

import fasttext

model = fasttext.train_supervised(input="cooking.train")
model.save_model("model_cooking.bin")

# predicting correctly
model.predict("Which baking dish is best to bake a banana cake ?")

# predicting wrongly
model.predict("Why not put knives in the dishwasher?")

model.test("cooking.valid")

model = fasttext.train_supervised(input="cooking.train", epoch=50)
model.test("cooking.valid")

model = fasttext.train_supervised(input="cooking.train", lr=1.0)
model.test("cooking.valid")

model = fasttext.train_supervised(input="cooking.train", lr=1.0, epoch=50)
model.test("cooking.valid")

model = fasttext.train_supervised(input="cooking.train", lr=1.0, epoch=50, wordNgrams=2)
model.test("cooking.valid")

model = fasttext.train_supervised(input="cooking.train", lr=0.5, epoch=50, wordNgrams=2, bucket=200000, dim=50, loss='ova')
model.test("cooking.valid")

model.predict("Which baking dish is best to bake a banana bread ?", k=-1, threshold=0.5)

model.predict("Why not put knives in the dishwasher?", k=-1, threshold=0.5)

